# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auth-Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  	pod 'KakaoSDKCommon'
  	pod 'KakaoSDKUser'
  	pod 'KakaoSDKAuth'

	pod 'Moya', '~> 14.0'
  	pod 'SnapKit', '~> 5.0.0'
  	pod 'Then'

  # Pods for Auth-Practice

end
